// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type HelloQueryInput struct {
	Name string `json:"name"`
}

type HelloQueryResult struct {
	Message string `json:"message"`
}
