// Code generated by entc, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in giautm.dev/awesome/ent/runtime.go

const (
	Version = "v0.10.2-0.20220507055527-429a5e5d917c"           // Version of ent codegen.
	Sum     = "h1:BSwsQFAJtwm1Mcme2F43VyDVuTdNz8T2/cs8ypV4A1A=" // Sum of ent codegen.
)
