// Code generated by entc, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in giautm.dev/awesome/ent/runtime.go

const (
	Version = "v0.9.2-0.20220104120740-6dc452f23d06"            // Version of ent codegen.
	Sum     = "h1:PXnGe1vXfCEtqA+OMHxBEDpOe8eiAcEAO9gZADPfgLE=" // Sum of ent codegen.
)
