// Code generated by ent, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in giautm.dev/awesome/ent/runtime.go

const (
	Version = "v0.10.2-0.20220612091225-1572f1eb145d"           // Version of ent codegen.
	Sum     = "h1:cTu4/fhsY9L7pXXqzxutyMjghitFutF+TuV5v2b/se0=" // Sum of ent codegen.
)
