// Code generated by entc, DO NOT EDIT.

package http

// Payload of a ent.User create request.
type UserCreateRequest struct {
	Age  *int    `json:"age"`
	Name *string `json:"name"`
}

// Payload of a ent.User update request.
type UserUpdateRequest struct {
	Age  *int    `json:"age"`
	Name *string `json:"name"`
}
