// Code generated by entc, DO NOT EDIT.

package ent

import (
	"entgo.io/ent/dialect/sql"
	"gocloud.dev/server/health/sqlhealth"
)

func (c *Client) HealthCheck() *sqlhealth.Checker {
	return sqlhealth.New(c.driver.(*sql.Driver).DB())
}
